language: rust

cache:
  - cargo

rust:
  - stable

branches:
  only:
    - master

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
  - cargo install-update -a

script:
  - mdbook build path/to/mybook && mdbook test path/to/mybook

deploy:
  #指定这是一份github pages的部署配置
  provider: pages

  skip_cleanup: true

  # token is set in travis-ci.org dashboard
  github_token: $GITHUB_TOKEN

  local-dir: path/to/mybook/book

  repo: edte/GoLand-documentation-cn
  
  keep-history: false

  target-branch: gh-pages

  email: deploy@travis-ci.org

  name: deployment-bot
