language: node_js

node_js:
  - "8"

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.npm


before_install:
  - export TZ='Asia/Shanghai'

install:
  - npm install -g gitbook-cli
  - gitbook install

script:
  - gitbook build . ./build

deploy:
  #指定这是一份github pages的部署配置
  provider: pages

  skip_cleanup: true

  # token is set in travis-ci.org dashboard
  github_token: $GITHUB_TOKEN

  local-dir: build

  repo: edte/GoLand-documentation-cn

  target-branch: gh-pages

  email: deploy@travis-ci.org

  name: deployment-bot
